### ISSUE TITLE
Figure out user authentication

### ISSUE THREAD

**Issue by erikjasso** [codeforpdx/recordexpungPDX#42] opened 2019-01-03 03:30 UTC

**Comment by maxkwallace** [comment] 2019-03-28 03:11
@a-ilango you are working on this, right? Would be good to assign this issue to yourself if yes. Maybe next meeting we can discuss what the authentication API will look like on the frontend.

**Comment by a-ilango** [comment] 2019-03-28 05:27
Yes, I was working on this. Let me assign it to myself.

> Maybe next meeting we can discuss what the authentication API will look like on the frontend

Sounds good. It is captured in the design document. We can add missing details if there are any.

**Comment by maxkwallace** [comment] 2019-03-28 05:42
@a-ilango ah, great! I forgot about the design document, thank you. I'll take a look again.

**Comment by maxkwallace** [comment] 2019-08-01 03:49
@a-ilango Hey Arun! Are you still working on this? Just wanted to check in.

**Comment by wittejm** [comment] 2019-08-01 05:57
@maxkwallace the /auth_token endpoint code is about finished with python tests passing, though I've just discovered that it's broken on the wsgi server (returns 400) and am looking into this.

**Comment by a-ilango** [comment] 2019-08-02 05:47
@maxkwallace Sorry, I'm not working on this. It's been busy for a while now but I'm hoping to contribute to this project again when I get some time in the future.

Thanks @wittejm for taking this up!

**Comment by erikjasso** [comment] 2019-08-29 02:56
@wittejm Can we close  this?

**Comment by wittejm** [comment] 2019-08-29 18:35
@erikjasso The only feature listed here that is missing from the app is to use persistent RSA keys in the prod environment, whereas the dev configuration works as intended (generating a random rsa key on app start). 

I suppose we could write a more specific issue and toss it into the project backlog, to unclutter the project board a bit. The feature is blocked on having the app use any prod configuration at all, since the wsgi.py launcher is hard-coded to use only the dev configuration

**Comment by wittejm** [comment] 2019-11-25 18:11
The only remaining feature here has been moved to #581

**Closed by wittejm** 2019-11-25 18:11 UTC
Labels: backend, frontend
