### ISSUE TITLE
Routing to demo bug

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1472] opened 2020-12-07 03:34 UTC
Reproduce:
1. If logged in, log out (clear cookies)
2. Go to https://recordsponge.com/partner-interest
3. Click the 'Check out the demo version' link
(or just go directly to https://recordsponge.com/demo-record-search)

Bug:
See that you're redirected to the OECI login instead of the demo view. Notice that you can successfully navigate to /demo-record-search from the OECI login link 'Check out the demo version'.

Also, when you are on /demo-record-search and refresh, you are directed to the OECI login instead of staying on the view.

**Comment by monocle** [comment] 2023-01-08 18:19
I have a fix for this:
https://github.com/monocle/recordexpungPDX/commit/7fb0babd267fb9b501ea395b142c31e544b943f2

**Comment by monocle** [comment] 2023-01-09 15:14
@KentShikama Yes, but I have a ton of changes on my fork and am not sure what would be the best way to get those back into the main repo.

At the moment, there are a couple of things that need to get fixed that have to do with the react router upgrade. After that, I could stop the conversion of the class components to functions+hooks, do some end to end testing and then merge the changes into main.

On the other hand, I could just finish the class component conversion and other changes (remove moment.js, @reach/disclosure, general refactoring) for one big merge.

The fastest thing, though, might be just to go back to the main branch and do the fix on that while leaving the other changes for a future date.

Let me know what you think is the best.

**Comment by KentShikama** [comment] 2023-01-09 15:25
@monocle I think it would be nice to get something small merged in as soon as possible so you get an idea of how the deployment process works here. It is basically all automated so there shouldn't be surprises, but I think it will be nice to ensure we are on the same page nonetheless.

**Comment by monocle** [comment] 2023-01-09 20:45
@KentShikama I pushed the changes to my fork on the 'demo-fix' branch. The commit message has the details. Unfortunately, Prettier added some changes, so the diffs might be a little noisy.

For testing, I did browser testing including checking requests with from submission to make sure the `demo` property was in the right state.

I was having problems with Docker errors and wasn't able to get the backend to start up to test end to end. I have very little Docker experience. It looked I needed to upgrade the alpine version?
<img width="704" alt="image" src="https://user-images.githubusercontent.com/120387970/211404327-93e32985-926e-40d9-8007-db17f5d46fab.png">

**Comment by KentShikama** [comment] 2023-01-10 01:16
Did you try `make up`?

**Comment by KentShikama** [comment] 2023-01-10 01:20
Also if you really just need a workaround to test you can just remove wkhtmltopdf _temporarily_ at https://github.com/codeforpdx/recordexpungPDX/blob/25a376c3fd5ab770d54a4734ee0b21c0c973ca9a/src/backend/Dockerfile#L14. It's only needed to generate the PDF, which you aren't touching with this PR.

**Closed** 2023-01-10 01:22 UTC
Labels: bug, frontend

**Comment by KentShikama** [comment] 2023-01-10 01:23
You can also test on https://dev.recordsponge.com/ once it's up. I might need to restart it.

**Comment by KentShikama** [comment] 2023-01-10 01:27
Just confirmed it works on https://dev.recordsponge.com/.

**Comment by KentShikama** [comment] 2023-01-10 01:30
@monocle Take a look yourself and tell me if it is what you expected. We can then cut a release.

**Comment by monocle** [comment] 2023-01-10 15:03
I tested on dev.recordsponge.com. Looks like things are working as they are in production.

Thanks @KentShikama !

**Comment by KentShikama** [comment] 2023-01-11 02:42
Great! I've cut a release and it should be on the prod site, recordsponge.com.
