### ISSUE TITLE
Add SearchResults Component in React

### ISSUE THREAD

**Issue by maxkwallace** [codeforpdx/recordexpungPDX#87] opened 2019-03-28 04:12 UTC
See the lower card under "Results for Firstname Lastname" on http://dev.huntermarcks.net/search/

This task is to build a Component that contains the HTML you see in the box with "Results for {firstname lastname}" at the top. This box has a header showing the name of the person searched for, with a variable-length list of results. The results sections should be implemented using one or more separate Components.

These Components do not need to interface with the backend data source. You are welcome to hard-code data into your Components that matches the mock data visible on http://dev.huntermarcks.net/search/

The UI should match the mockups as well.

### This task is done when...
 - SearchResults and other Components (as needed) to create the search results view exist in React

![Record Expunge Search UI Data v2](https://user-images.githubusercontent.com/6887982/55674238-b1898900-5866-11e9-8f8c-aa2ae42312bf.png)

**Comment by hmarcks** [comment] 2019-05-13 05:23
Closing because it's a duplicate of https://github.com/codeforpdx/recordexpungPDX/issues/86

**Comment by maxkwallace** [comment] 2019-05-14 17:15
@hmarcks I didn't intend for this to be a duplicate. My bad if the issue was confusing.

My intention was for #86 to be only the top card containing the input fields for the search, and this issue to be only the lower card containing the search. These should be separate components in React. Let me know if that doesn't make sense or you think the issues should be structured differently.

**Comment by hmarcks** [comment] 2019-05-14 17:20
@maxkwallace gotcha, I was thinking #64 would be the integration work, perhaps these should be combined.

**Comment by maxkwallace** [comment] 2019-05-14 17:28
@hmarcks ah, I lost track of #64 , my bad. I was trying to break things down a bit more. For a project like this it's really crucial that each task is super small so no one get stuck waiting for a big chunk of work they have a dependency on. 

The way this works with Redux is that the search and results Components actually never communicate directly with each other, which is good, because then they can be treated independently.

The search component just puts the results into the redux store, at which point the results component displays them. That work can be started without the backend but we'd be guessing a bit at the format of the data. 

My personal opinion is that #64 be the integration task to finish the feature after the backend is returning results in response to HTTP requests from the frontend, but I'm open to other options as well.

**Comment by hmarcks** [comment] 2019-05-14 18:17
Sounds good to me, thanks @maxkwallace !

**Comment by SteelFace87** [comment] 2019-07-04 16:58
I am starting to work on this

**Comment by maxkwallace** [comment] 2019-07-04 18:11
@SteelFace87 awesome! Thanks for letting us know.

**Comment by NickSchimek** [comment] 2019-12-18 19:55
@SteelFace87 is this complete? Or is there still work to be done?

**Comment by wittejm** [comment] 2020-02-08 17:13
Completed

**Closed by wittejm** 2020-02-08 17:13 UTC
Labels: frontend
