### ISSUE TITLE
Create new Eligibility types: "Eligible but on case with [Ineligible/Future Eligible] charge"

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#1656] opened 2023-01-20 16:39 UTC
Currently all eligible charges are grouped together and classified as "Eligible." However, we want to distinguish between (i) eligible charges on cases that are completely eligible (and therefore the entire case is eligible) and (ii) eligible charges on cases where there is at least one non-eligible charge. 

We further want to distinguish between the types of non-eligibility, i.e.  eligible charges on cases where is
(i) at least one Ineligible charge
(ii) at least one Future Eligible charge
(if a case has both Ineligible and Future Eligible charges, then only state the Ineligible charge)

**Eligible on case with Ineligible charge**
**Eligible on case with charge eligible [date of latest eligibility]**

These should be listed in the Summary Panel after Eligible charges. **Eligible on case with charge eligible [date of latest eligibility]** should be listed in closest -> furthest date of eligibility
so that the order is

Possibly Eligible
Ineligible
Eligible
Eligible on case with Ineligible charge
Eligible on case with charge eligible [date (earliest)]
...
Eligible on case with charge eligible [date (latest)]
etc.

**Comment by monocle** [comment] 2023-01-25 15:28
#1298 seems to be related. That ticket was tagged as `Backend`, but if all of the information is already sent to the frontend via the `expungement_result` JSON data field, then the display logic can be handled without new backend code. 

Here's an example from one of the John Common charges:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/120387970/214603863-238982a5-5bc2-4c50-a511-3cda801a80ca.png">

**Comment by wittejm** [comment] 2023-03-08 21:09
@michaelzhang43 a few questions:

1. Should the expanded view be affected? Since charges are grouped by case it's easy to see when an eligible charge is on a case with a future eligible or ineligible charge, so it seems redundant to say so.

2. Should the charge detail display be affected?

3. Should Generate Paperwork no longer generate the paperwork for these charges?

**Comment by wittejm** [comment] 2023-03-08 21:34
Another way to phrase the same question 3: do we generate paperwork for a case only if every charge on that case is eligible?

**Comment by michaelzhang43** [comment] 2023-03-08 23:43
1./2. Indeed would be redundant, but I'd like to have both the expanded view and the case detail panels reflect the new status - I did a couple "test runs" and found myself wanting to look at both of these to evaluate whether expunging those particular charges were worth it. Having the charges at issue in a different color than the eligible charges on other cases would help to distinguish them 

3. Yes, thanks for reminding me of this point. The main issue inspiring this request is that users are printing off and filing all paperwork without considering the partial eligibility component. I'm not sure the most efficient way to quickly add these to the print list. Would it be efficient to add a button next to each charge that says "Add to Print List" that converts these to Eligible Now?

**Comment by wittejm** [comment] 2023-03-09 20:53
@michaelzhang43 I made the simplest change which was to adjust the main summary view, and it looks like this: 

<img width="705" alt="Screenshot 2023-03-09 at 12 33 57 PM" src="https://user-images.githubusercontent.com/2104990/224150185-e0f78871-d543-43e5-bec6-cb9dfbf90994.png">

This was fairly simple because the summary is computed after the initial expungement analysis--- so we're able to obtain these "secondary" definitions of eligibility. Changing the way the detail view looks would be tougher because I think it means replicating this "secondary" round of analysis whole cloth. I haven't worked with the expanded summary view but I suspect it would be the same. It's hard to estimate how hard this is.

The change to make it optional to generate paperwork for partially eligible cases wouldn't be too crazy. There are some design questions like where to put the buttons/checkboxes and it would be good to get Hunter's input.

A question for now is, should I put in the change I've already made above? Or would it be misleading because paperwork for those cases is still being generated?

And a usage question: did this feature come up because a client may or may not be interested in partially expunging a given case?

**Comment by michaelzhang43** [comment] 2023-03-10 16:24
Wow - glad to hear that this variable is already being computed on some level!

Could you put it into dev? Would love to test drive it for feel, and see how the other clinic people people about it.

And it's much more that partial expungements on a future eligible case is kind of in bad form with the DA's office. Basically we'd be asking them to redact a portion of the case (the DAs are required but don't always go through the actual case files and redact the aspects of the expunged charges), only to later go back and seal the whole case. Similarly, we'd like to be more cognizant of filing partial expungements in general, especially now that the software is being used by people around the State that we're not monitoring. For example, it's probably not worth it to expunge a dismissed Assault 4 charge on a case with an Assault 2 conviction.

**Comment by ejunge** [comment] 2023-03-11 07:29
I am not sure I understand the way the problem is phrased or the comments, but my initial issue was the problem of future eligible cases, where currently RecordSpong separates the dismissed or otherwise eligible charges from the future eligible charges on a single case. We can't submit paperwork on dismissed or "eligible" charges on a future eligbile case because the DA will reject it.  This means we have to train volunteers to sort out the eligible parts of that case, that is, not print them out even if they say "eligible" in Record Sponge. It would be great if all parts of a future eligible case were listed together. Sorry if I wasn't clear, or this is already understood. Thanks

**Comment by wittejm** [comment] 2023-03-16 00:49
@ejunge This change doesn't quite group eligible charges together with the future-eligible charges on the same case, but it does pull those eligible charges out of the "eligible" section of the summary, into their own section. 

@michaelzhang43 The changes in the record summary are in dev. Please take a look when you have a chance!

**Comment by ejunge** [comment] 2023-03-16 17:21
Just so I am clear, you are not saying connected dismissed charges are eligible when balance is owed on convictions in same case?Sent from my iPhoneOn Mar 16, 2023, at 9:07 AM, michaelzhang43 ***@***.***> wrote:﻿
Since we're having further explanations by email to accomodate the other users, I'll just post some points here that probably don't require much additional input. To begin, the behavior right now is to separate "Eligible X date if Balance Paid" (convictions) from "Eligible on case with charge Eligible X date If Balance Paid" (dismissals). Would be better to have the charges in the later category join the former category.
The below is from a real case, I've left out the case details. Message me separately for the info
Eligible Jan 6, 2025 (2)
Identity Theft (CONVICTED) Charged Dec 1, 2019
Unlawful Possession of Methamphetamine (CONVICTED) Charged Dec 1, 2019
Eligible Jan 6, 2025 If Balance Paid (2)
COUNTY – $827.0
Identity Theft (CONVICTED) Charged Oct 29, 2015
COUNTY – $1350.68
Theft in the First Degree (CONVICTED) Charged Sep 23, 2008

Eligible on case with charge Eligible Jan 6, 2025 If Balance Paid (3)
COUNTY – $827.0
Forgery in the Second Degree (DISMISSED) Charged Oct 29, 2015
COUNTY – $1350.68
Theft in the First Degree (DISMISSED) Charged Oct 27, 2008
Theft in the First Degree (DISMISSED) Charged Oct 16, 2008

**Comment by wittejm** [comment] 2023-03-16 19:06
> Just so I am clear, you are not saying connected dismissed charges are eligible when balance is owed on convictions in same case?

@ejunge If balance is owed on a case with eligible or future eligible charges then all of the eligible or future eligible charges on that case are listed in summary sections that include "If Balance Paid", regardless of whether those charges are dismissals or convictions

**Comment by wittejm** [comment] 2023-03-16 20:43
@michaelzhang43 I merged the section of "eligible on case with future-eligible charge" into the "future eligible" section. I also added a well-defined ordering

**Comment by ejunge** [comment] 2023-03-16 20:45
ThxSent from my iPhoneOn Mar 16, 2023, at 1:43 PM, Jordan Witte ***@***.***> wrote:﻿
@michaelzhang43 I merged the section of "eligible on case with future-eligible charge" into the "future eligible" section. I also added a well-defined ordering

**Comment by wittejm** [comment] 2023-03-21 19:41
Completed in various linked PRs.

**Closed by wittejm** 2023-03-21 19:41 UTC
Labels: Complexity: 3
